// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHPb-T0WKYog7tXSmNRimKcQIXJ-mYAQU',
    appId: '1:542869507309:web:0bff068e1c54a4182f10e4',
    messagingSenderId: '542869507309',
    projectId: 'cabineflow-4bca7',
    authDomain: 'cabineflow-4bca7.firebaseapp.com',
    storageBucket: 'cabineflow-4bca7.firebasestorage.app',
    measurementId: 'G-6S0WP62G19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo-GlziqJS2vQrIkV58bbvtCUu8_8DI0U',
    appId: '1:542869507309:android:127acb5d3519466f2f10e4',
    messagingSenderId: '542869507309',
    projectId: 'cabineflow-4bca7',
    storageBucket: 'cabineflow-4bca7.firebasestorage.app',
  );
}
